apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-wordpress
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress-deployment
  minReplicas: 2       
  maxReplicas: 5   
  targetCPUUtilizationPercentage: 50 
# Scalling definido por CPU, quando a cpu da pod atingir 50%, começa a escalar mais pods