apiVersion: v1
kind: PersistentVolumeClaim ## volume usado pelo pod
metadata:
  name: pv-claim-mysql
  namespace: microcontainers
  labels:
    app: vl-mysql
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi