apiVersion: v1
kind: PersistentVolumeClaim ## volume usado pelo pod
metadata:
  name: pv-claim-wordpress
  namespace: microcontainers
  labels:
    app: vl-wordpress
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi