apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql ## criando um mount para o serviço do worpress 
  namespace: microcontainers
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/mysql"
