apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wordpress ## criando um mount para o serviço do worpress 
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/wordpress"
