apiVersion: apps/v1
kind: Deployment
metadata:
  name:  wordpress-deployment
  namespace: microcontainers
  labels:
    app:  wordpress
    type: frontend
spec:
  selector:
    matchLabels:
      app: wordpress
      type: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app:  wordpress
        type: frontend
    spec:
      # definindo e configurando o deploy da pod do wordpress
      containers:
      - name:  wordpress
        image:  arm64v8/wordpress:5.8 # definindo a imagem do wordpress
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 350Mi
        env:
          - name: WORDPRESS_DB_HOST
            value: mysql:3306
          - name: WORDPRESS_DB_USER
            value: useradmin
          - name: WORDPRESS_DB_NAME
            value: wordpressdb
          - name: WORDPRESS_DB_PASSWORD # password por ser um dado sensível, a leitura é feita a partir do secret
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: user-password
        ports:
        - containerPort:  80
          name:  http-port
        volumeMounts:
          - mountPath: /var/www/html/
            name: wordpress-storage
      volumes:
        - name: wordpress-storage
          persistentVolumeClaim:
            claimName: pv-claim-wordpress
      restartPolicy: Always