# Use root/example as user/password credentials
version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: useradmin
      WORDPRESS_DB_PASSWORD: useradmin
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - ./wordpresshtml:/var/www/html

  database:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: useradmin
      MYSQL_PASSWORD: useradmin
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./mysqldb:/var/lib/mysql
