apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: microcontainers
spec:
  selector:
    app: wordpress
    type: frontend
  type: LoadBalancer
  ports:
  - name: http-sv-port
    protocol: TCP
    port: 80
    targetPort: http-port 